project:
  type: book
  output-dir: _book

license: "CC BY-NC-SA"

copyright:
  holder: "Prof. Elvis do A. Soares"
  year: 2026

book:
  title: "Química Quântica para Moléculas e Sólidos"
  subtitle: "Notas de aula e aplicações computacionais"
  author: "Prof. Elvis do A. Soares"
  output-file: quimica-quantica

  page-footer:
    left: |
      Química Quântica © 2026 Elvis do Amaral Soares.
    right: |
      Licenciado sob [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).

  chapters:
    - index.qmd
    - prefacio.qmd
    - part: "Fundamentos da Mecânica Quântica"
      chapters:
        - capitulos/1-bases_experimentais.qmd
        - capitulos/2-postulados.qmd
    - part: "Estrutura Eletrônica de Átomos e Moléculas"

  downloads: [pdf, epub]
  repo-url: https://github.com/elvissoares/COQ875-QuimicaQuantica
  repo-branch: livro-quarto
  repo-actions: [source, issue]

bibliography: referencias/referencias.bib

format:
  html:
    theme:
      dark: darkly
      light: flatly
    respect-user-color-scheme: true
    toc: true
    number-sections: true
    code-fold: false
  pdf:
    documentclass: scrreprt
    number-sections: true
    toc: true

  epub:
    toc: true

execute:
  freeze: auto
