# Método de Hartree-Fock

Usando o @eq-principio-variacional, podemos escolher uma função de onda eletrônica tentativa $\ket{\Psi_e}$ tal que o valor esperado para o Hamiltoniano eletrônico molecular $\hat{H}_e$ possa ser calculado como
$$
E_0 \leq \braket{\Psi_e|\hat{H}_e|\Psi_e} 
$$
onde $E_0$ é a energia do estado fundamental eletrônico e $\hat{H}_e$ é  o Hamiltoniano eletrônico molecular definido, a partir da @eq-problema_eletronico, como 
$$
\hat{H}_e =  \sum_{i=1}^N \hat{h}_i + \frac{1}{2}\sum_{i=1}^N\sum_{j\neq i}^N \frac{1}{|\boldsymbol{r}_i-\boldsymbol{r}_j|}+ \frac{1}{2}\sum_{A=1}^M\sum_{B \neq A}^M \frac{Z_A Z_B}{|\boldsymbol{R}_A-\boldsymbol{R}_B|}
$$
onde $\hat{h}_i$ é o operador de 1 elétron que inclui a energia cinética do elétron e a interação coulombiana elétron-núcleo, escrito na forma 
$$
    \hat{h}_i=-\frac{1}{2}\nabla_i^2 - \sum_{A=1}^M \frac{Z_A}{|\boldsymbol{r}_i-\boldsymbol{R}_A|}, 
$$

A função de onda eletrônica de muitos elétrons $\ket{\Psi_e}$ na base de posições e spins deve ser escrita como $\Psi_e(\boldsymbol{x}_1,\boldsymbol{x}_2,\ldots,\boldsymbol{x}_N)$ onde $\boldsymbol{x}_i=\boldsymbol{r}_i,\sigma_i$ é uma variável que representa a posição $\boldsymbol{r}_i$ e o spin $\sigma_i$ do elétron $i$. Sabemos que tal função de onda pode ser escrita em termos do produto de funções de onda para 1 elétron, $\psi_j(\boldsymbol{x}_i)$, onde $i$ representa o elétron e $j$ o estado de 1 elétron, e com a condição que $\braket{\psi_i|\psi_j} = \delta_{ij}$. É comum denominarmos o conjunto $\psi_j(\boldsymbol{x}_i)$ como **conjunto de spin-orbitais molecular**.

Para satisfazer o **princípio de exclusão de Pauli** devemos construir uma função de onda que seja totalmente anti-simétrica sobre permutações de 2 elétrons, tal que $\Psi_e(\boldsymbol{x}_1,\boldsymbol{x}_2,\ldots,\boldsymbol{x}_N) = - \Psi_e(\boldsymbol{x}_2,\boldsymbol{x}_1,\ldots,\boldsymbol{x}_N)$. Para resolver esse problema, Slater propôs que a função de onda de $N$ elétrons seja escrita na forma de um determinante de funções de onda de 1 elétrons. O **determinante de Slater** é escrito como 
$$\begin{aligned}
    \Psi_e(\boldsymbol{x}_1,\boldsymbol{x}_2,\ldots,\boldsymbol{x}_N) = \frac{1}{\sqrt{N!}} \begin{vmatrix}
        \psi_1(\boldsymbol{x}_1) & \psi_2(\boldsymbol{x}_1) & \dots & \psi_N(\boldsymbol{x}_1) \\
        \psi_1(\boldsymbol{x}_2) & \psi_2(\boldsymbol{x}_2) & \dots & \psi_N(\boldsymbol{x}_2) \\
        \vdots & \vdots & & \vdots \\
        \psi_1(\boldsymbol{x}_N) & \psi_2(\boldsymbol{x}_N) & \dots & \psi_N(\boldsymbol{x}_N)
    \end{vmatrix}
\end{aligned}$${#eq-determinante_Slater}
onde a 1ª linha representa os $N$ estados possíveis para o elétron $i=1$, a 2ª linha representa os $N$ estados possíveis para o elétron $i=2$, e assim por diante. O termo $\frac{1}{\sqrt{N!}}$ vem da condição de normalização da função de onda $\Psi_e(\boldsymbol{x}_1,\boldsymbol{x}_2,\ldots,\boldsymbol{x}_N)$ dos $N$ elétrons ($N!$ é o número de permutações possíveis de $N$ elétrons). 

Usando o determinante de Slater, podemos mostrar as chamadas **regras de Slater-Condon** tal que para o operador de 1 elétron temos que 
$$\begin{aligned}
\left\langle \Psi_e \left| \sum_{i=1}^{N} \hat{h}_i \right| \Psi_e \right\rangle &= \sum_{i=1}^{N} \langle \psi_i | \hat{h}_1 | \psi_i \rangle \\
&= \sum_{i=1}^{N}\int \psi_i^*(\boldsymbol{x}_1) \hat{h}_1 \psi_i (\boldsymbol{x}_1)\ \text{d}\boldsymbol{x}_1,
\end{aligned}$$
enquanto que para o operador de interação elétron-elétron, que é um operador de 2 elétrons, temos que 
$$\begin{aligned}
\left\langle \Psi_e \left| \frac{1}{2} \sum_{i=1}^{N} \sum_{j \neq i}^{N} \frac{1}{|\boldsymbol{r}_i - \boldsymbol{r}_j|} \right| \Psi_e \right\rangle =\ & \frac{1}{2} \sum_{i=1}^{N} \sum_{j \neq i}^{N} \left\langle \psi_i \psi_j \left| \frac{1}{|\boldsymbol{r}_1 - \boldsymbol{r}_2|} \right| \psi_i \psi_j \right\rangle \nonumber \\
& - \frac{1}{2} \sum_{i=1}^{N} \sum_{j \neq i}^{N} \left\langle \psi_i \psi_j \left| \frac{1}{|\boldsymbol{r}_1 - \boldsymbol{r}_2|} \right| \psi_j \psi_i \right\rangle
\end{aligned}$${#eq-eletron-eletron-HF}
onde 
$$\begin{aligned}
\left\langle \psi_i \psi_j \left| \frac{1}{|\boldsymbol{r}_1 - \boldsymbol{r}_2|} \right| \psi_k \psi_l \right\rangle = \iint \psi_i^*(\boldsymbol{x}_1) \psi_j^*(\boldsymbol{x}_2) \frac{1}{|\boldsymbol{r}_1 - \boldsymbol{r}_2|} \psi_k(\boldsymbol{x}_1) \psi_l(\boldsymbol{x}_2) \ \text{d}\boldsymbol{x}_1 \text{d}\boldsymbol{x}_2,
\end{aligned}$$
de modo que o primeiro termo da @eq-eletron-eletron-HF é a interação direta de Coulomb e o segundo termo é a interação de troca. Essa interação de troca não possui análogo na física clássica e tem sua origem na indistinguibilidade dos elétrons. 

Afim de encontrar os melhores spin-orbitais para determinar a energia do estado fundamental do nosso sistema, devemos utilizar o teorema variacional novamente. Podemos construir uma Lagrangeana na seguinte forma 
$$\begin{aligned}
    \mathcal{L}(\{\psi_i\}) = \braket{\Psi_e|\hat{H}_e|\Psi_e} - \sum_{ij} \epsilon_{ij} (\braket{\psi_i|\psi_j}-\delta_{ij})
\end{aligned}$$
onde o primeiro termo é o valor esperado do Hamiltoniano eletrônico molecular sem a interação núcleo-núcleo e o segundo termo aparece como um multiplicador de Lagrange $\epsilon_{ij}$ afim de satisfazer a condição de orto-normalização dos spin-orbitais. Efetuando a derivada variacional do tipo
$$
\frac{\delta \mathcal{L}(\{\psi_i\})}{\delta \bra{\psi_k}} = 0
$$
chegamos a 
$$\begin{aligned}
    \hat{F} \ket{\psi_k} = \left[\hat{h} + \hat{J} - \hat{K} \right] \ket{\psi_k} = \epsilon_k \ket{\psi_k},
\end{aligned}$${#eq-HF}
que são as **equações de Hartree-Fock** para os $N$ spin-orbitais. O operador $\hat{F}$ é denominado operador de Fock, e pode ser escrito em termo de $\hat{h}$ e de dois novos operadores $\hat{J}$ e $\hat{K}$. O operador de Coulomb $\hat{J}$ é definido como sendo
$$\begin{aligned}
\hat{J} = \sum_{i=1}^N \left \langle \psi_i(\boldsymbol{x}') \left|\frac{1}{|\boldsymbol{r} - \boldsymbol{r}'|}\right|\psi_i(\boldsymbol{x}') \right \rangle = \sum_{i=1}^N \int \frac{|\psi_i(\boldsymbol{x}')|^2}{|\boldsymbol{r} - \boldsymbol{r}'|} \ \text{d}\boldsymbol{x}',
\end{aligned}$$
enquanto o operador de troca $\hat{K}$ é escrito como
$$\begin{aligned}
\hat{K}\ket{\psi_k}= \sum_{i=1}^N \left \langle \psi_i(\boldsymbol{x}') \left|\frac{1}{|\boldsymbol{r} - \boldsymbol{r}'|}\right|\psi_k(\boldsymbol{x}') \right \rangle \ket{\psi_i} = \sum_{i=1}^N \left[ \int  \frac{\psi_i^*(\boldsymbol{x}') \psi_k(\boldsymbol{x}')}{|\boldsymbol{r} - \boldsymbol{r}'|}\ \text{d}\boldsymbol{x}'\right] \psi_i(\boldsymbol{x}).
\end{aligned}$$

As soluções $\ket{\psi_k}$ e $\epsilon_k$ são os spin-orbitais moleculares e as energias orbitais, respectivamente. Embora as equações de Hartree-Fock apareçam na forma de um problema de autovalor, devemos notar que o operador de Fock depende das próprias soluções $\ket{\psi_k}$. Assim, tal problema deve ser resolvido por outras técnicas. 